### ISSUE TITLE
F-Droid version

### ISSUE THREAD

**Issue by j5k** [farscrl/dicziunari#4]
Thank you so much for the app. I really like it! 

Is it possible to publish a F-Droid version? Would be very useful.

**Comment by gion-andri** [comment]
Hi @j5k, 
Currently, we are unfortunately not yet allowed to publish the database with the data for the app on GitHub. Therefore, it is not yet possible to build the app for F-Droid. 
However, as soon as we are allowed to publish all the data, we will look for an F-Droid build.

**Comment by j5k** [comment]
Nice to hear that the intention is there. Thanks!
